import shutil
import unittest

from cictikz.schematic import Instance, Port, Schematic, Wire
from cictikz.symbols import SymbolRegistry
from cictikz.writers.tikz import write_tikz
from cictikz.writers.xschem import write_sch
from cictikz.writers.xschem_sym import write_sym


def common_source_amp() -> Schematic:
    sch = Schematic("amp_cs")
    sch.add(Instance("GND", "vground", pos=(0, 0)))
    sch.add(
        Instance(
            "M1", "lvnmos", pos=(0, 0), args=["M1", "$v_i$"],
            conns={"source": "vss", "gate": "vi", "drain": "vo"},
        )
    )
    sch.add(
        Instance("R1", "vresistor", pos=(0, 1.6), args=["$R_L$"],
                 conns={"minus": "vo", "plus": "vdd"})
    )
    sch.add(Instance("VDD", "vsupply", pos=(0, 3.2)))
    sch.add(Wire(points=[(0, 1.6), (0.8, 1.6)], net="vo"))
    sch.add(Port("vo", pos=(0.8, 1.6), direction="out"))
    return sch


class TestTikzWriter(unittest.TestCase):
    def setUp(self):
        self.sch = common_source_amp()

    def test_emits_macros_and_banner(self):
        out = write_tikz(self.sch)
        self.assertIn("Generated by cictikz", out)
        self.assertIn(r"\draw (0,0) \lvnmos{M1}{$v_i$};", out)
        self.assertIn(r"\draw (0,1.6) \vresistor{$R_L$};", out)
        self.assertIn(r"\draw (0,1.6) -- (0.8,1.6);", out)
        self.assertIn(r"\portOut{vo}", out)

    def test_junction_dot_where_three_meet(self):
        # drain pin + resistor minus pin + wire endpoint all at (0, 1.6)
        out = write_tikz(self.sch)
        self.assertIn(r"\fill (0,1.6) circle (0.075);", out)

    def test_default_args_from_instance_name(self):
        sch = Schematic("t")
        sch.add(Instance("M9", "vnmos", pos=(0, 0)))
        self.assertIn(r"\vnmos{M9}", write_tikz(sch))

    def test_wrong_arg_count_raises(self):
        sch = Schematic("t")
        sch.add(Instance("M1", "lvnmos", args=["only-one"]))
        with self.assertRaises(ValueError):
            write_tikz(sch)

    def test_rot_rejected(self):
        sch = Schematic("t")
        sch.add(Instance("M1", "vnmos", rot=1))
        with self.assertRaises(ValueError):
            write_tikz(sch)

    @unittest.skipUnless(shutil.which("pdflatex"), "pdflatex not on PATH")
    def test_output_compiles(self):
        from cictikz import render as r

        result = r.render_tex(r.wrap_body(write_tikz(self.sch)))
        self.assertTrue(result.ok, msg="\n".join(result.errors))


class TestXschemWriter(unittest.TestCase):
    def setUp(self):
        self.sch = common_source_amp()
        self.out = write_sch(self.sch)

    def test_header_and_records(self):
        self.assertTrue(self.out.startswith("v {xschem version"))
        for record in ["G {}", "K {}", "V {}", "S {}", "E {}"]:
            self.assertIn(record, self.out)

    def test_instances_and_labels(self):
        self.assertIn("C {sky130_fd_pr/nfet_01v8.sym} 0 0 0 0 {name=M1}", self.out)
        # drain at (0, 1.6) -> (0, -64): lab_pin carries the net there
        self.assertIn("C {devices/lab_pin.sym} 0 -60 0 0", self.out)  # snapped to 10
        self.assertIn("lab=vo", self.out)
        self.assertIn("C {devices/opin.sym} 30 -60 0 0 {name=p1 lab=vo}", self.out)

    def test_named_wire_becomes_net_record(self):
        self.assertIn("N 0 -60 30 -60 {lab=vo}", self.out)

    def test_unknown_pin_raises(self):
        sch = Schematic("t")
        sch.add(Instance("M1", "vnmos", conns={"emitter": "x"}))
        with self.assertRaises(ValueError):
            write_sch(sch)


class TestSymWriter(unittest.TestCase):
    def test_ota_sym(self):
        reg = SymbolRegistry.load()
        out = write_sym(reg.get("cicOta"))
        self.assertIn("type=subcircuit", out)
        for pin in ["inp", "inn", "outp", "outn"]:
            self.assertIn(f"name={pin} dir=", out)
        # inp at (0,0), outn at (2.6, 0) -> x 104 snaps to 100
        self.assertIn("B 5 97.5 -2.5 102.5 2.5 {name=outn dir=out}", out)


class TestRoundTripDict(unittest.TestCase):
    def test_json_round_trip(self):
        sch = common_source_amp()
        again = Schematic.from_dict(sch.to_dict())
        self.assertEqual(again.to_dict(), sch.to_dict())

    def test_unknown_key_rejected(self):
        with self.assertRaises(TypeError):
            Schematic.from_dict(
                {"name": "t", "instances": [{"name": "M1", "symbol": "vnmos", "bogus": 1}]}
            )

    def test_nets_from_conns_and_wires(self):
        sch = common_source_amp()
        nets = sch.nets(SymbolRegistry.load())
        self.assertIn(("M1", "drain"), nets["vo"])
        self.assertIn(("R1", "minus"), nets["vo"])


if __name__ == "__main__":
    unittest.main()
