"""Schematic IR -> dialect TikZ.

Emits a bare figure body in the cictikz macro vocabulary (compile with
``render.wrap_body``). Wires are polyline ``--`` segments; junction
dots appear where three or more things meet, per the house convention
that undotted crossings are not connected.
"""

from __future__ import annotations

from collections import Counter

from ..schematic import SNAP, Schematic
from ..symbols import SymbolRegistry

BANNER = "% Generated by cictikz. Edit the schematic that produced it, not this file.\n"

PORT_MACRO = {"in": "\\portIn", "out": "\\portOut", "inout": "\\portIn"}


def _fmt(v: float) -> str:
    s = f"{v:.5g}"
    return "0" if s == "-0" else s


def _pt(p) -> str:
    return f"({_fmt(p[0])},{_fmt(p[1])})"


def write_tikz(sch: Schematic, registry: SymbolRegistry | None = None) -> str:
    registry = registry or SymbolRegistry.load()
    out = [BANNER]

    for inst in sch.instances:
        if inst.symbol.startswith("unknown:"):
            # Foreign xschem symbol with no TikZ mapping: a labelled box
            # keeps the schematic readable and the instance visible.
            x, y = inst.pos
            out.append(
                f"\\draw {_pt((x - 0.6, y - 0.4))} rectangle {_pt((x + 0.6, y + 0.4))};"
            )
            short = inst.symbol.removeprefix("unknown:").rsplit("/", 1)[-1].removesuffix(".sym")
            label = f"{inst.name}: {short}".replace("_", "\\_")
            out.append(f"\\node[anchor=center] at {_pt(inst.pos)} {{{label}}};")
            continue
        sym = registry.get(inst.symbol)
        if inst.flip and sym.mirror:
            sym = registry.get(sym.mirror)  # flip is the mirrored macro variant
        elif inst.flip:
            raise ValueError(
                f"{inst.name}: flip is not expressible - symbol '{sym.name}' "
                "has no mirrored variant"
            )
        if inst.rot:
            # The macros cannot rotate; draw unrotated but say so, since
            # the layout will differ from the xschem original.
            out.append(f"% NOTE: {inst.name} had rot={inst.rot} in xschem; drawn unrotated.")
        args = list(inst.args)
        if sym.nargs and not args:
            # First documented argument is the instance name by library
            # convention; remaining arguments default to empty.
            args = [inst.name] + [""] * (sym.nargs - 1)
        if len(args) != sym.nargs:
            raise ValueError(
                f"{inst.name}: {sym.macro} takes {sym.nargs} argument(s), got {len(args)}"
            )
        invocation = sym.macro + "".join("{%s}" % a for a in args)
        out.append(f"\\draw {_pt(inst.pos)} {invocation};")

    for wire in sch.wires:
        if len(wire.points) < 2:
            raise ValueError("wire needs at least two points")
        out.append("\\draw " + " -- ".join(_pt(p) for p in wire.points) + ";")

    for port in sch.ports:
        if _drawn_by_macro(port, sch, registry):
            continue  # e.g. the lvnmos gate label already draws this port
        out.append(f"\\draw {_pt(port.pos)} {PORT_MACRO[port.direction]}{{{port.net}}};")

    for lab in sch.labels:
        out.append(f"\\node[anchor={lab.anchor}] at {_pt(lab.pos)} {{{lab.text}}};")

    for dot in _junctions(sch, registry):
        out.append(f"\\fill {_pt(dot)} circle (0.075);")

    return "\n".join(out) + "\n"


def _drawn_by_macro(port, sch: Schematic, registry: SymbolRegistry) -> bool:
    """True when a macro argument already draws this port (arg_ports),
    so emitting a \\portIn would double it."""
    for inst in sch.instances:
        if inst.symbol.startswith("unknown:"):
            continue
        sym = registry.get(inst.symbol)
        for argno, pin in (sym.arg_ports or {}).items():
            if len(inst.args) < int(argno) or not inst.args[int(argno) - 1].strip():
                continue
            pdef = next(p for p in sym.pins if p.name == pin)
            px = inst.pos[0] + pdef.grid_xy[0]
            py = inst.pos[1] + pdef.grid_xy[1]
            if abs(px - port.pos[0]) <= SNAP and abs(py - port.pos[1]) <= SNAP:
                return True
    return False


def _junctions(sch: Schematic, registry: SymbolRegistry) -> list[tuple[float, float]]:
    """Points where >= 3 connection ends coincide: pin positions named in
    conns, wire endpoints, and port positions."""

    def snap(p):
        return (round(p[0] / SNAP) * SNAP, round(p[1] / SNAP) * SNAP)

    counts = Counter()
    pin_points = sch.pin_points(registry)
    for inst in sch.instances:
        for pin in inst.conns:
            counts[snap(pin_points[(inst.name, pin)])] += 1
    for wire in sch.wires:
        counts[snap(wire.points[0])] += 1
        counts[snap(wire.points[-1])] += 1
    for port in sch.ports:
        counts[snap(port.pos)] += 1
    return sorted(p for p, n in counts.items() if n >= 3)
