#!/usr/bin/env python3
"""Run the dialect reader over a corpus of figures and report coverage.

Figures are classified before scoring: generated data plots (the
tikzplot banner, or pgfplots axes) are not schematics and are never
expected to parse, so they are counted separately rather than as
failures. Usage:

    python3 scripts/corpus_report.py /path/to/tikz [-v]
"""

import collections
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))
from cictikz.readers.tikz import read_tikz  # noqa: E402


def classify(text: str) -> str:
    if "Generated by py/tikzplot.py" in text:
        return "plot"
    if re.search(r"\\begin\{(axis|groupplot)\}|\\nextgroupplot", text):
        return "plot"
    return "figure"


def main():
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "tikz")
    verbose = "-v" in sys.argv
    files = sorted(f for f in root.glob("**/*.tex") if "lib" not in f.name)
    plots, ok, failed = [], [], []
    reasons = collections.Counter()
    for f in files:
        text = f.read_text()
        if classify(text) == "plot":
            plots.append(f)
            continue
        try:
            read_tikz(text)
            ok.append(f)
        except Exception as e:
            failed.append(f)
            reasons[re.sub(r"line \d+: ", "", str(e))[:58]] += 1
            if verbose:
                print(f"FAIL {f.name}: {e}")
    total = len(ok) + len(failed)
    print(f"corpus: {len(files)} files, {len(plots)} generated plots excluded")
    print(f"schematics parsed: {len(ok)}/{total} = {100*len(ok)/max(total,1):.0f}%")
    print("\ntop failure reasons:")
    for msg, n in reasons.most_common(10):
        print(f"{n:4d}  {msg}")


if __name__ == "__main__":
    main()
