"""Generate docs/libraries.md: a reference for the domain libraries.

The main schematic vocabulary (cictikz_lib) has its own curated gallery
in symbols.md; the other packaged libraries are documented here
mechanically: each library's own header comment, its macros with
argument counts, its numeric constants, and a rendered specimen for
every macro that compiles standalone with guessed arguments. Macros
that only make sense composed into a larger figure get listed without
an image rather than faked.

Run from the repo root: python3 scripts/gen_lib_docs.py
"""

import re
from pathlib import Path

from cictikz import render as r
from cictikz.render import lib_names

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "libraries"

LIB_TITLES = {
    "boot_lib.tex": "boot — the bootstrapped switch",
    "constellation_lib.tex": "constellation — modulation constellations",
    "dacsm_lib.tex": "dacsm — DAC state machines",
    "esd_lib.tex": "esd — ESD networks and zaps",
    "gmc_lib.tex": "gmc — gm-C filter blocks",
    "mos_lib.tex": "mos — MOSFET cross-section cartoons",
    "plane_lib.tex": "plane — s/z-plane diagrams",
    "rdac_lib.tex": "rdac — resistor-DAC blocks",
    "sc_lib.tex": "sc — switched-capacitor circuits",
    "sfg_lib.tex": "sfg — signal-flow and block diagrams",
    "spec_lib.tex": "spec — spectra sketches",
}


def header_comment(text: str) -> str:
    """The library's own leading comment block, stripped of decoration."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            if lines:
                break
            continue
        if not stripped.startswith("%"):
            break
        clean = stripped.lstrip("%").strip()
        if clean and not set(clean) <= {"-", "%", "#"}:
            lines.append(clean)
    return "\n".join(lines)


def macros_of(text: str) -> list[tuple[str, int]]:
    out = []
    for m in re.finditer(r"\\newcommand\*?\{\\(\w+)\}(?:\[(\d+)\])?\{", text):
        name, n = m.group(1), int(m.group(2) or 0)
        # numeric constants are listed separately
        tail = text[m.end() : m.end() + 40]
        if n == 0 and re.match(r"-?[\d.]+\}", tail):
            continue
        out.append((name, n))
    return out


def constants_of(text: str) -> list[tuple[str, str]]:
    return re.findall(r"\\newcommand\{\\(\w+)\}\{(-?[\d.]+)\}", text)


def guess_args(n: int) -> str:
    """Positional macros in these libraries lead with coordinates and end
    with labels; (0,0)-anchored numbers plus $x$ labels cover most."""
    vals = ["0", "0", "1", "$x$", "$y$", "$z$", "$w$"][:n]
    return "".join("{%s}" % v for v in vals)


def try_render(name: str, nargs: int):
    args = guess_args(nargs)
    for body in (
        f"\\draw (0,0) \\{name}{args};",  # path-fragment style
        f"\\{name}{args}",  # absolute \draw-internal style
    ):
        result = r.render_tex(r.wrap_body(body))
        if result.ok and result.pdf_path.stat().st_size > 1800:
            return result.pdf_path
    return None


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Domain libraries\n",
        "<!-- Generated by scripts/gen_lib_docs.py - edit the library",
        ".tex files and re-run, not this file. -->\n",
        "Beyond the [schematic vocabulary](symbols.md), the package ships",
        "eleven domain libraries, inlined by `wrap_body` alongside",
        "`cictikz_lib` (macro names are unique across all twelve).",
        "Specimens below are auto-rendered with guessed arguments; macros",
        "without an image only make sense composed into a larger figure.\n",
    ]
    root = ROOT / "src" / "cictikz" / "data" / "tex"
    for lib in lib_names():
        if lib == "cictikz_lib.tex":
            continue
        text = (root / lib).read_text()
        title = LIB_TITLES.get(lib, lib)
        lines.append(f"\n## {title}\n")
        head = header_comment(text)
        if head:
            lines.append("> " + head.replace("\n", "\n> ") + "\n")
        consts = constants_of(text)
        if consts:
            lines.append(
                "Constants: "
                + ", ".join(f"`\\{n}` = {v}" for n, v in consts) + "\n"
            )
        for name, nargs in macros_of(text):
            sig = f"\\{name}" + "{...}" * nargs
            pdf = try_render(name, nargs)
            lines.append(f"### {name}\n")
            lines.append(f"`{sig}`\n")
            if pdf:
                r.pdf_to_svg(pdf, OUT / f"{name}.svg")
                lines.append(f'<img src="libraries/{name}.svg" alt="{name}">\n')
                print("rendered", name)
            else:
                print("listed  ", name)
    (ROOT / "docs" / "libraries.md").write_text("\n".join(lines) + "\n")
    print("wrote docs/libraries.md")


if __name__ == "__main__":
    main()
