"""Generate docs/symbols.md and one SVG per symbol from the registry.

Run from the repo root after changing symbol metadata:

    python3 scripts/gen_symbol_docs.py

Each symbol is rendered through its own macro with representative
arguments, so the gallery is also a compile test of the whole library.
"""

from pathlib import Path

from cictikz import render as r
from cictikz.symbols import SymbolRegistry

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "symbols"

# Representative invocation arguments per macro that takes any
ARGS = {
    "vnmos": "{M1}", "vmnmos": "{M1}", "vpmos": "{M1}", "vmpmos": "{M1}",
    "lvnmos": "{M1}{$v_i$}", "lvmnmos": "{M1}{$v_i$}",
    "lvpmos": "{M1}{$v_i$}", "lvmpmos": "{M1}{$v_i$}",
    "vresistor": "{$R$}", "hresistor": "{$R$}",
    "vcapacitor": "{$C$}", "hcapacitor": "{$C$}",
    "vimpedance": "{$Z$}", "himpedance": "{$Z$}",
    "vvsource": "{$V$}",
    "portIn": "{$v_i$}", "portmIn": "{$v_i$}", "portOut": "{$v_o$}",
    "portDiffIn": "{$v_i$}", "portDiffOut": "{$v_o$}",
    "portOutDown": "{$v_o$}", "curDown": "{$i_o$}", "portCurDown": "{$i_o$}",
    "hinv": "{X1}", "cicH": "{$H(s)$}",
    "cicNand": "{g}", "cicAnd": "{g}", "cicNor": "{g}", "cicOr": "{g}",
    "cicInv": "{g}", "cicBuf": "{g}", "cicInvM": "{g}",
    "cicOtaSWP": "{$+$}{$-$}{$+$}{$-$}", "cicOtaSSWP": "{$+$}{$-$}",
    "filtLP": "{$R$}{$C$}", "filtHP": "{$C$}{$R$}",
    "filtActLP": "{$R$}{$C$}", "filtActZ": "{$Z_1$}{$Z_2$}",
}

CATEGORIES = [
    ("Transistors", lambda n: "mos" in n or n == "trNmos"),
    ("Passives", lambda n: any(k in n for k in ("resistor", "capacitor", "impedance"))),
    ("Sources and rails", lambda n: n in ("vvsource", "vground", "vsupply")),
    ("Ports", lambda n: n.startswith("port") or n.startswith("curDown")),
    ("OTAs and blocks", lambda n: n.startswith("cic") or n == "hinv"),
    ("Current mirrors", lambda n: n.startswith("cm")),
    ("Filters", lambda n: n.startswith("filt")),
    ("Other", lambda n: True),
]


def categorise(names):
    seen = set()
    for title, match in CATEGORIES:
        bucket = [n for n in names if n not in seen and match(n)]
        seen.update(bucket)
        if bucket:
            yield title, bucket


def main():
    reg = SymbolRegistry.load()
    OUT.mkdir(parents=True, exist_ok=True)

    failures = []
    for name in reg.names():
        sym = reg.get(name)
        body = f"\\draw (0,0) {sym.macro}{ARGS.get(name, '')};"
        result = r.render_tex(r.wrap_body(body))
        if not result.ok:
            failures.append((name, result.errors[:1]))
            continue
        r.pdf_to_svg(result.pdf_path, OUT / f"{name}.svg")
        print("rendered", name)
    if failures:
        raise SystemExit(f"failed: {failures}")

    lines = [
        "# Symbol library\n",
        "<!-- Generated by scripts/gen_symbol_docs.py - edit the symbol",
        "YAML (via scripts/gen_symbols.py) and re-run, not this file. -->\n",
        "All coordinates are figure units (`\\grid` = 1.6, one transistor",
        "tall, y up) relative to the macro entry point. Macros are path",
        "fragments: they start at the current point and compose inside one",
        "`\\draw`. Every rendering below is produced by the macro itself,",
        "so this page doubles as a compile test of the library.\n",
    ]

    names = reg.names()
    lines.append("| symbol | description |")
    lines.append("|---|---|")
    for name in names:
        lines.append(f"| [`\\{name}`](#{name.lower()}) | {reg.get(name).description} |")
    lines.append("")

    for title, bucket in categorise(names):
        lines.append(f"\n## {title}\n")
        for name in bucket:
            sym = reg.get(name)
            lines.append(f"### {name}\n")
            lines.append(f'<img src="symbols/{name}.svg" alt="{name}">\n')
            lines.append(f"{sym.description}\n")
            lines.append("```latex")
            lines.append(sym.signature())
            lines.append("```\n")
            lines.append(f"entry `{list(sym.entry)}` — exit `{list(sym.exit)}`\n")
            if sym.pins:
                lines.append("| pin | position | direction |")
                lines.append("|---|---|---|")
                for p in sym.pins:
                    lines.append(f"| {p.name} | {list(p.grid_xy)} | {p.direction} |")
                lines.append("")
            if sym.nodes:
                lines.append(
                    "anchors: " + ", ".join(f"`{n}`" for n in sym.nodes) + "\n"
                )
            if sym.exports:
                lines.append(
                    "exported coordinates: "
                    + ", ".join(f"`{k}`" for k in sym.exports) + "\n"
                )
            if sym.xschem and sym.xschem.get("sym"):
                lines.append(f"xschem: `{sym.xschem['sym']}`\n")
            if sym.example:
                lines.append("```latex")
                lines.append(sym.example)
                lines.append("```\n")

    (ROOT / "docs" / "symbols.md").write_text("\n".join(lines) + "\n")
    print(f"wrote docs/symbols.md ({len(names)} symbols)")


if __name__ == "__main__":
    main()
